server:
    port: 8081
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/codetickets-db
        jdbcUrl: jdbc:mysql://localhost:3306/codetickets-db
        username: myuser
        password: mypass
    jpa:
        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
    batch:
        jdbc:
            initialize-schema: always
        job:
            enabled: false
logging:
    level:
        org.springframework.batch: INFO

