# Use the official MySQL image
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=batch
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypass

# Expose the default MySQL port
EXPOSE 3306

# Use a volume to persist data
VOLUME /var/lib/mysql
