server:
  port: 8082
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch
    jdbcUrl: jdbc:mysql://localhost:3306/batch
    username: myuser
    password: mypass
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 20000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          fetch_size: 1000
          batch_versioned_data: true
        order_updates: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
logging:
  level:
    org.springframework.batch: INFO
    org.hibernate:
      .sql: DEBUG
      .type.descriptor.sql.BasicBinder: TRACE

